@startuml
participant ユーザー
participant メイン
participant サブ
participant リスト
participant CSVファイル

== 新規追加 ==

ユーザー -> メイン : 「新規追加」を押下
activate ユーザー
activate メイン
メイン -> メイン : 新規追加のメソッドを呼び出す

メイン -> ユーザー : 新規追加画面を表示
ユーザー -> メイン : エンジニア情報を入力し「保存」を押下
メイン->メイン : 情報を編集できないようにロックする
メイン->サブ : サブスレッドを立てる
activate サブ
メイン -> サブ : 入力した情報を渡す（形式チェックをサブに任せる）


サブ -> サブ : 入力内容をチェック（形式確認）
alt 形式が違う場合
    サブ -> メイン : 形式が違う
    メイン -> ユーザー : 形式が違う項目を赤く表示する
    メイン->ユーザー : 再入力を促す
    メイン->サブ : 再度サブスレッドを立て、形式チェックを行う
end

サブ -> CSVファイル : バックアップ用CSVファイルを作成

サブ -> CSVファイル : CSVファイルをロックする
サブ->CSVファイル : 新規追加した情報をCSVファイルに追加


alt CSVファイルに追加中にエラーが起きた場合
    CSVファイル-->サブ : 追加失敗
    サブ->CSVファイル : 保存用CSVファイルを削除
    サブ->CSVファイル : バックアップ用 CSVファイルの名前を"employee_data.csv" に変更
    サブ->CSVファイル : CSVファイルのロックを解除する
    サブ->メイン: CSVファイルに追加失敗
    メイン->ユーザー : 追加失敗ダイアログ
    メイン->サブ : サブスレッドを閉じる
    deactivate サブ
end

CSVファイル --> サブ : 保存完了
activate サブ
サブ->リスト : 新たなエンジニア情報をリストに追加
サブ-> CSVファイル : バックアップ用 CSVファイルを削除
サブ -> CSVファイル : ロックの解除

サブ -> メイン : 保存完了を渡す
メイン -> サブ : サブスレッドを閉じる
deactivate サブ
メイン -> ユーザー : 保存完了のダイアログ表示 一覧画面を表示する（更新）
deactivate メイン
deactivate ユーザー
@enduml