@startuml
actor ユーザー
participant メイン
participant サブ
participant ログ
participant リスト
participant 選択リスト
participant CSVファイル
participant バックアップ用CSVファイル

== 削除 ==

ユーザー -> メイン : 削除したいエンジニア情報を選択（複数選択可）
activate ユーザー
activate メイン
メイン->選択リスト : 選択したエンジニアの社員IDを選択リストに載せる
メイン -> ユーザー : 選択した情報をグレーアウトにする
メイン->ユーザー : 「削除」を活性化
ユーザー -> メイン : 「削除」を押下
メイン->ユーザー : 「削除」を非活性化
メイン -> ユーザー : 削除確認ダイアログを表示
ユーザー -> メイン : 「はい」を押下
メイン -> ユーザー : 一覧画面の表示(更新前)

メイン -> サブ : サブスレッドを立てる
activate サブ
サブ-> バックアップ用CSVファイル : バックアップ用のCSVファイルを作成
サブ -> CSVファイル : CSVファイルにロックをかける
サブ->選択リスト : 選択リストにある社員IDを読み取る
サブ -> CSVファイル : 削除対象のエンジニア情報をCSVファイルから削除（ひとつずつ）

alt CSVファイル削除中にエラーが起きた場合
    CSVファイル-->サブ : 削除失敗
    サブ->CSVファイル :　保存用CSVファイルを削除
    サブ->CSVファイル : バックアップ用CSVファイルの名前を"employee_data.csv" に変更
    サブ-> CSVファイル : CSVファイルのロックを解除
    サブ->メイン: CSVファイルに追加失敗
    サブ->サブ : サブスレッドを閉じる
    deactivate サブ
    メイン->ユーザー : 追加失敗ダイアログ
end

サブ --> リスト : 選択リストのにある社員IDのエンジニア情報をを削除　ここはループ
activate サブ
サブ->選択リスト : 選択リストを削除
サブ->CSVファイル : バックアップ用 CSVファイルを削除
サブ -> メイン : 更新されたリストを渡す
メイン->サブ : サブスレッドを閉じる
deactivate サブ
メイン -> ユーザー : 削除完了ダイアログを表示し、更新後のリストを反映
deactivate メイン
deactivate ユーザー
@enduml