@startuml
participant ユーザー
participant メイン
participant サブ
participant リスト
participant CSVファイル

== 編集 ==

ユーザー -> メイン : 編集したいエンジニア情報を選択
activate ユーザー
activate メイン

メイン -> ユーザー : 詳細画面を表示（選択されたエンジニア情報を表示）
ユーザー -> メイン : 新しいエンジニア情報を入力し「保存」を押下
メイン->メイン : 情報を編集できないようにロックする
メイン->サブ : サブスレッドを立てる
activate サブ
メイン -> サブ : 入力した情報を渡す（形式チェックをサブに任せる）

サブ -> サブ : 入力内容をチェック（形式確認）
alt 形式が違う場合
    サブ -> メイン : 形式が違う
    メイン -> ユーザー : 形式が違う項目を赤く表示する
    メイン->ユーザー : 再入力を促す
    メイン->サブ : 再度サブスレッドを立て、形式チェックを行う
end

サブ -> CSVファイル : バックアップ用CSVファイルを作成

サブ -> CSVファイル : CSVファイルをロックする
サブ->CSVファイル : 編集した情報をCSVファイルに上書き

alt CSVファイルに上書き中にエラーが起きた場合
    CSVファイル-->サブ : 上書き失敗
    サブ->CSVファイル : 保存用CSVファイルを削除
    サブ->CSVファイル : バックアップ用 CSVファイルの名前を"employee_data.csv" に変更
    サブ->CSVファイル : CSVファイルのロックを解除する
    サブ->メイン: CSVファイルに上書き失敗
    メイン->ユーザー : 編集失敗ダイアログ
    メイン->サブ : サブスレッドを閉じる
    deactivate サブ
end

CSVファイル --> サブ : 上書き完了
activate サブ
サブ->リスト : 編集されたエンジニア情報をリストに反映
サブ-> CSVファイル : バックアップ用 CSVファイルを削除
サブ -> CSVファイル : ロックの解除

サブ -> メイン : 編集完了を渡す
メイン -> サブ : サブスレッドを閉じる
deactivate サブ
メイン -> ユーザー : 編集完了のダイアログ表示 一覧画面を表示する（更新）
deactivate メイン
deactivate ユーザー
@enduml