@startuml
actor ユーザー
participant メイン
participant サブ
participant ログ

==アプリ終了==

group アプリ終了 ESCキー
    ユーザー -> メイン : Escキーを押す
    activate ユーザー
    activate メイン
    メイン -> ユーザー : 終了確認ダイアログを表示
    ユーザー -> メイン : 終了を選択
    deactivate ユーザー
    メイン -> メイン : アプリ画面を閉じる
    メイン -> サブ : 現在動作しているスレッドを確認
    activate サブ

    alt 動作しているものがある場合
       サブ -> サブ : 順番に処理する
    end

    サブ --> メイン : 動作しているものはない
    サブ->サブ : サブスレッドを閉じる
    deactivate サブ
    メイン -> ログ : アプリ終了ログ記録
    ログ --> メイン : ログ記録完了
    メイン -> メイン : アプリケーション終了
    deactivate メイン
end

@enduml