@startuml
actor ユーザー
participant メイン
participant サブ
participant リスト
participant 選択リスト
participant 外部ファイル

== CSV出力 ==

ユーザー->メイン : CSV出力したいエンジニア情報を選択（複数選択可）
activate ユーザー
activate メイン
メイン->選択リスト : 選択した情報を選択リストに追加
メイン->メイン : 選択状態にする
メイン->ユーザー : 選択した情報をグレーアウトにする
メイン->ユーザー : 出力を活性化
ユーザー->メイン : 「出力」を押下
メイン->ユーザー : 出力を非活性化

メイン->ユーザー : ファイルチューザー表示
ユーザー->メイン : 出力先のフォルダーを選択
メイン->サブ : サブスレッドを立てる
activate サブ
メイン->ユーザー : 一覧画面を表示


サブ->サブ : ファイル名を作成 日時間秒
loop ファイル存在確認
  サブ->外部ファイル : 同じファイル名があるか確認
  外部ファイル-->サブ : 同じ目名前のファイルがある
  サブ->サブ : ファイル名をもう一度作成
end
外部ファイル-->サブ : 同じファイル名なし
サブ-> 外部ファイル : 新規ファイルを作成

サブ->外部ファイル : 外部ファイルにロックをかける


loop
  サブ->選択リスト : 選択リストの社員IDを取得
  サブ->外部ファイル : 選択したエンジニア情報を行に保存
  サブ->選択リスト : 次の情報が残っているか確認
end

alt エラー時
  外部ファイル-->サブ : 保存の失敗
  サブ->外部ファイル : ロックの解除
  サブ->メイン : 出力失敗を渡す
  サブ->サブ : サブスレッドを閉じる
  メイン->ユーザー : 出力失敗のダイアログを表示
end

外部ファイル-->サブ : 保存完了
サブ->外部ファイル : 外部ファイルのロックを解除する
サブ->メイン : CSVファイルに保存完了
サブ->サブ : サブスレッドを閉じる
deactivate サブ
メイン->選択リスト : 選択リストの内容を削除
メイン->ユーザー : エンジニアのグレーアウトを解除する
メイン->ユーザー : 保存完了のダイアログ　
deactivate メイン
deactivate ユーザー
@enduml