@startuml

participant ユーザー
participant メイン
participant サブ
participant リスト
participant 検索リスト

==検索==
ユーザー->メイン: 検索項目を入力 検索」ボタンをクリック
activate ユーザー
activate メイン
メイン->サブ: サブスレッドを立てる
activate サブ
サブ->検索リスト: 検索リストを作成
サブ->リスト: 検索項目の条件に当てはまる情報を読み込む
サブ->検索リスト: リストから読み込んだ情報を検索リストに追加
検索リスト->サブ: 検索結果を返す
メイン<-サブ: 検索結果のエンジニアリストを渡す
deactivate サブ
メイン->ユーザー: エンジニアを表示
deactivate メイン

==エラーハンドリング==
検索リスト->メイン: 結果がない場合、エラーメッセージを返す
メイン->ユーザー: 「該当するエンジニアが見つかりません」

@enduml