actor ユーザー
participant メイン
participant サブ
participant リスト
participant ソートリスト

== ソート処理 ==
ユーザー -> メイン : 並び替え項目を選択
activate ユーザー
activate メイン
メイン->サブ : サブスレッドを立てる
サブ->ソートリスト : リストの情報をディープコピー
サブ -> ソートリスト : 並び替えを実行
ソートリスト -> サブ : 並び替え完了
サブ->メイン : ソートリストをの情報を渡す
メイン -> ユーザー : ソートされた情報を表示
deactivate メイン



@enduml
