@startuml
actor ユーザー
participant メイン
participant サブ
participant リスト
participant 選択リスト
participant 外部ファイル

== テンプレートCSV出力 ==

ユーザー->メイン : 「テンプレート出力」を選択
activate ユーザー
activate メイン
メイン -> ユーザー : ファイルチューザー表示
ユーザー -> メイン : 出力ファイルを選択
メイン -> ユーザー : 一覧画面を表示
メイン->サブ : サブスレッドを立てる
activate サブ


サブ->サブ : ファイル名を作成 employee_template.csv
alt 同じファイル名あり
サブ->外部ファイル : 同じ名前のファイルがあるか確認
サブ->メイン : 同じファイル名前のファイルがある
メイン->サブ: サブスレッドを閉じる
メイン->ユーザー: 出力エラーダイアログ
end


外部ファイル->サブ : ファイル作成完了

サブ->外部ファイル : 外部ファイルにロックをかける


alt エラー時
  外部ファイル-->サブ : 出力の失敗
  サブ->外部ファイル : 作成した新規ファイルを削除
  サブ->メイン : 出力失敗を渡す
  メイン->サブ : サブスレッドを閉じる
  メイン->ユーザー : 出力失敗のダイアログを表示
end

外部ファイル-->サブ : 出力完了
サブ->外部ファイル : 外部ファイルのロックを解除する
メイン->サブ : サブスレッドを閉じる
deactivate サブ
メイン->ユーザー : 保存完了のダイアログ  
deactivate メイン
deactivate ユーザー
@enduml