@startuml

participant ユーザー
participant メイン
participant サブ
participant リスト
participant CSVファイル

== 新規追加 ==

ユーザー -> メイン : 「新規追加」を押下
activate ユーザー
activate メイン
メイン -> メイン : 新規追加のメソッドを呼び出す

メイン -> ユーザー : 新規追加画面を表示
ユーザー -> メイン : エンジニア情報を入力し「保存」を押下
メイン->メイン : 情報を編集できないようにロックする
メイン->サブ : サブすサブスレッドを立てる
activate サブ
メイン -> サブ : 入力した情報を渡す（形式チェックをサブに任せる）


サブ -> サブ : 入力内容をチェック（形式確認）
alt 形式が違う場合
    サブ -> ユーザー : 形式が違う箇所を赤く表示させて再入力を求める
    ユーザー -> サブ : 情報を再入力し「保存」を押下
    サブ -> サブ : 再度入力内容をチェック（形式確認）
end

サブ -> メイン : 入力内容が正しい場合、情報を渡す

メイン -> サブ : サブスレッドを立てる
メイン -> サブ : 入力した情報を渡す
サブ -> CSVファイル : CSVファイルをロックする
サブ -> CSVファイル : 新規追加した情報をCSVファイルを開き保存

alt 追加にエラーが起きた場合
    サブ-->メイン : 追加失敗
    メイン->
end
CSVファイル --> サブ : 追加の成功

サブ->リスト : 新規追加した情報をリストに追加

リスト --> サブ : 保存完了
サブ -> CSVファイル : ロックの解除
サブ -> メイン : 保存完了を渡す
サブ -> サブ : サブスレッドを閉じる
deactivate サブ
メイン -> ユーザー : 保存完了のダイアログ表示 一覧画面を表示する（更新）
deactivate メイン

@enduml