@startuml
actor ユーザー
participant メイン
participant サブ
participant ログ
participant リスト
participant 選択リスト
participant CSVファイル

== 削除 ==

ユーザー -> メイン : 削除したいエンジニア情報を選択（複数選択可）
メイン->選択リスト : 選択したエンジニア情報をリストに載せる
メイン -> ユーザー : 選択した情報をグレーアウトにする
ユーザー -> メイン : 「削除」を押下
メイン -> ユーザー : 削除確認ダイアログを表示
ユーザー -> メイン : 「はい」を押下
メイン -> メイン : 削除のメソッドを呼び出す
メイン -> ユーザー : 一覧画面の表示(更新前)
メイン -> サブ : サブスレッドを立てる

サブ->選択リスト : 選択リストにある情報を読み取る
サブ -> ログ : 削除したエンジニア情報をログに残す（社員ID）
サブ -> リスト : 削除対象のエンジニア情報をリストから削除
サブ -> サブ : 新たなリストを作成
サブ -> サブ : 新たなリストを読み込む
サブ -> CSVファイル : CSVファイルにロックをかける
サブ -> CSVファイル : 新たなリストをCSVファイルに上書き保存
CSVファイル --> サブ : 上書き保存完了
サブ -> CSVファイル : CSVファイルのロック解除
サブ->選択リスト : 選択リストを削除
サブ -> メイン : 更新されたリストを渡す
メイン -> ユーザー : 削除完了ダイアログを表示し、更新後のリストを反映

@enduml