@startuml

actor ユーザー
participant メイン
participant サブ
participant リスト
participant 選択リスト
participant 外部ファイル

==CSV出力==

ユーザー->メイン : CSV出力したいエンジニア情報を選択（複数選択可）
activate ユーザー
activate メイン
メイン->選択リスト : 選択した情報を選択リストに追加
メイン->メイン : 選択状態にする
メイン->ユーザー : 選択した情報をグレーアウトにする
ユーザー->メイン : 「出力」を押下
メイン->メイン : CSV出力メソッドを呼び出す
メイン->外部ファイル : ファイルチューザーに出てくるものを読み取る
外部ファイル-->メイン : 読み取り完了
メイン->ユーザー : 読み取ったファイルチューザー表示
ユーザー->メイン : 出力先のファイルを選択
メイン->ユーザー : 一覧画面を表示
メイン->サブ : サブスレッドを立てる
activate サブ
サブ->外部ファイル : 外部ファイルにロックをかける
サブ->選択リスト : 選択した情報を読み取る

loop
サブ->リスト : 選択したエンジニア情報を取得
リスト-->サブ : 選択した情報
サブ->外部ファイル : 選択したエンジニア情報を行に保存
サブ->サブ : 選択した情報がまだあるか確認
end

外部ファイル-->サブ : 保存完了
サブ->外部ファイル : 外部ファイルのロックを解除する
サブ->選択リスト : 選択リストの内容を削除
サブ->メイン : CSVファイルに保存完了
サブ->サブ :サブスレッドを閉じる
deactivate サブ
メイン->ユーザー : 保存完了のダイアログ　
deactivate メイン
deactivate ユーザー
@enduml