@startuml

participant ユーザー 
participant メイン 
participant サブ 

==検索==
ユーザー->メイン: 検索項目を入力して「検索を押下」
activate ユーザー
activate メイン
メイン->サブ: 検索のメソッド呼び出す
activate サブ
サブ->サブ: 条件に当てはまるエンジニアを探す
サブ->メイン: 条件に当てはまるエンジニアを返す
deactivate サブ
メイン->ユーザー: エンジニアを表示
deactivate メイン

@enduml